### PR TITLE
Mission Timer

### PR DESCRIPTION
**Pull request by jagatfx**
- added mission timer
- changed text colors to black
- added missing font asset

### CODE REVIEW

**Comment by jagatfx** [comment]
@DylanB123 feel free to merge this if it works for you

**Comment by DylanB123** [comment]
I see a timer, and black text. and the font in the asset folder. Going to merge.

**Comment by jagatfx** [comment]
@DylanB123 I just merged, hopefully not messing you up

**Comment by DylanB123** [comment]
All good on on my end.

**Pull request merged**
